### ISSUE TITLE
Evaluación página personal

### ISSUE THREAD

**Issue by gootyfer** [AilatanGH/AilatanGH.github.io#1]
### A destacar
- Diseño de la web
- Favicon
- Estructura de ficheros
- Organización del código CSS: comentarios, indentación

### A mejorar
- Semántica de las clases para el ancho de las barras de skills. Mejor `.fifty-percent` que `.four`, ¿verdad?

### Valoración final
4 / 4
Mínimos conseguidos pero además buen diseño de la web y buena organización de código. ¡Enhorabuena por el excelente trabajo!

**Comment by AilatanGH** [comment]
Muchas gracias!! tomo nota para mejorar en esos aspectos ;)

**Comment by gootyfer** [comment]
OK. Pues cierro entonces este issue ;)
